### ISSUE TITLE
Support repeating on more intervals

### ISSUE THREAD

**Issue by willmot** [humanmade/repeatable-posts#1]
Currently weekly is hardcoded, we should support more intervals.

At a minimum we might as well support the built in WordPress cron intervals, `hourly`, `twice-daily`, `daily`, `weekly`, `fortnightly`, `monthly`.

**Comment by noplanman** [comment]
Were you thinking just the built in ones or all intervals available (also the ones added via filters)?

**Comment by willmot** [comment]
I'd probably go with using the standard core ones but passed through a filter so that people can easily add / remove them just for this plugin. Open to suggestions though 👍

**Comment by noplanman** [comment]
Core only has `hourly`, `twicedaily`, `daily` and `weekly` by default, as far as I can see.
To repeat a post hourly seems a bit crazy to me, but hey, that's just me ;-)

I agree with having a filter for this plugin only, but to display all schedules in the drop down.
Maybe show the ones added via plugin filter at the top, then all other custom / internal ones?

**Comment by willmot** [comment]
Maybe we should just skip the core ones and go with our own list of daily, weekly, monthly with a filter for now

**Comment by noplanman** [comment]
:+1: Oki doki, that makes sense.

**Comment by willmot** [comment]
Implemented in #10 and released in [0.4](https://github.com/humanmade/repeatable-posts/releases/tag/0.4)
