### ISSUE TITLE
Custom Post Types

### ISSUE THREAD

**Issue by vinyllicker** [humanmade/repeatable-posts#39]
This looks to be exactly what I need for my site but it doesn't currently work with custom post types. Would this be possible to implement? I have a custom post type called track and need it to work with that.
Cheers.
Rick

**Comment by vinyllicker** [comment]
Worked it out thanks. Located in the hm-post-repeat.php file if anybody is interested, just add it to the array e.g.
/**
 * The post types the feature is enabled on
 *
 * By default only posts have the feature enabled but others can be added with the `hm_post_repeat_post_types` filter.
 *
 * @return array An array of post types
 */
function repeating_post_types() {

	/**
	 * Enable support for additional post types.
	 *
	 * @param string[] $post_types Post type slugs.
	 */
	return apply_filters( 'hm_post_repeat_post_types', array( **'track',** 'post' ) );

**Comment by willmot** [comment]
Glad you found it 👍
