### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by rmccue** [humanmade/repeatable-posts#4]
* [x] `HM_Post_Repeat` should probably be a namespace rather than a singleton class these days. The [singleton instance](https://github.com/humanmade/repeatable-posts/blob/4483d8bb1bacb1f4cd941fe90e465368157329a2/hm-post-repeat.php#L37) also isn't assigned to anything, which means another plugin couldn't unhook it.
* [x] Public methods should be explicitly `public`
* [ ] [Closing PHP tag](https://github.com/humanmade/repeatable-posts/blob/4483d8bb1bacb1f4cd941fe90e465368157329a2/class-hm-post-repeat.php#L46) should be on new line
* [x] Translations need to be escaped throughout
* [x] [Using `_` instead of `_e`](https://github.com/humanmade/repeatable-posts/blob/4483d8bb1bacb1f4cd941fe90e465368157329a2/class-hm-post-repeat.php#L62)
* [x] [Conditionals in HTML/mixed mode](https://github.com/humanmade/repeatable-posts/blob/4483d8bb1bacb1f4cd941fe90e465368157329a2/class-hm-post-repeat.php#L54) should use long-style `if: else: endif`
* [x] In `publish_box_ui`, `self::is_repeating_post` result should be stored, since it's used a bunch of times.
* [x] [Missing translation](https://github.com/humanmade/repeatable-posts/blob/4483d8bb1bacb1f4cd941fe90e465368157329a2/class-hm-post-repeat.php#L71)
* [x] [Data passed to `wp_insert_post`](https://github.com/humanmade/repeatable-posts/blob/4483d8bb1bacb1f4cd941fe90e465368157329a2/class-hm-post-repeat.php#L173) needs to be slashed (i.e. `wp_insert_post( wp_slash( $next_post ) )`)
* [x] [Data passed to `add_post_meta`](https://github.com/humanmade/repeatable-posts/blob/4483d8bb1bacb1f4cd941fe90e465368157329a2/class-hm-post-repeat.php#L191) needs to be slashed
* [x] [List of strings](https://github.com/humanmade/repeatable-posts/blob/4483d8bb1bacb1f4cd941fe90e465368157329a2/class-hm-post-repeat.php#L216-L220) can be documented a bit more simply: `@param string[] $post_types Post type slugs.`
* [x] [`$_POST['ID']` isn't checked for existence](https://github.com/humanmade/repeatable-posts/blob/4483d8bb1bacb1f4cd941fe90e465368157329a2/class-hm-post-repeat.php#L237)
* [x] In `is_repeat_post`, [the `$post_id` parameter](https://github.com/humanmade/repeatable-posts/blob/4483d8bb1bacb1f4cd941fe90e465368157329a2/class-hm-post-repeat.php#L257) isn't actually used. (Also, the `get_post` call should be assigned to a var for multiple uses)

**Comment by willmot** [comment]
> HM_Post_Repeat should probably be a namespace rather than a singleton class these days. The singleton instance also isn't assigned to anything, which means another plugin couldn't unhook it.

@rmccue as in just drop the class and go procedural functions namespaced under `HM/RepeatablePost`?

**Comment by rmccue** [comment]
Yup. `HM\Repeatable_Posts` is fine too if you want to keep the underscore

**Comment by willmot** [comment]
>  Closing PHP tag should be on new line

Is this covered in WP Code Standards? I've always closed on the last line of PHP.

Why is:
``` PHP
<img src="" />

<?php echo 'foo'; ?>

<img src="" />
```

Any different to:

```PHP
<?php if ( $foo ) {

    $src = 'bar'; ?>

    <img src="" />

<?php } ?>
```

**Comment by dashaluna** [comment]
>  HM_Post_Repeat should probably be a namespace rather than a singleton class these days. The singleton instance also isn't assigned to anything, which means another plugin couldn't unhook it.

@rmccue hm, could you explain a bit more why you're suggesting not to use singleton class? I'd thought using a singleton class is good approach, the thing is missing here is that the instance should be created on `plugins_loaded` action. Even if it's not a class, still should be included on `plugins_loaded`, right?

**Comment by rmccue** [comment]
> Is this covered in WP Code Standards? I've always closed on the last line of PHP.

[This comment](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/comment-page-1/#comment-9227) is the closest. In this specific instance though, it's not on an opening tag, so it's better practice to have it on a newline. (Imagine it along the lines of not having multiple statements per line.)

> hm, could you explain a bit more why you're suggesting not to use singleton class?

Classes in general should only be used when you need an object; i.e. you've got something, and you're performing actions on it. Singletons are a special case of this where you only _need_ one of them. A classic example of a singleton is a database connection; you perform actions on the database, but you only need one connection (most of the time).

Here, the class is just to group everything together, there's no real object that's having actions performed on it.

**Comment by willmot** [comment]
Closing as I've fixed everything. See c432260 for most of the items and then https://github.com/humanmade/repeatable-posts/commit/9a2145674f68269e5a21a6f3be154eb2083408b6 covers off switching from a class to a namespace.

Thanks for the thourough review @rmccue, I learned stuff. Now going to write my own CMS.

**Comment by rmccue** [comment]
As is tradition.
